## PANDAS INTRO

In [ ]:
# Power Bi / Tableau -> Dashboard tool / Data Analysis (Application)
# Python + Code version Excel + Data visualzation tools + Streamlit

In [ ]:
# uv add pandas
# !pip install pandas

# What is Pandas?

Pandas is an open-source Python library for data manipulation and analysis. It gives you 
powerful, fast, flexible, and expressive data structures designed to work with structured data.

It is built on top of NumPy, and its name comes from “Panel Data” (econometrics term for multidimensional data).

# Why Pandas? What problem does it solve?

### Before Pandas:

People used raw Python lists, dictionaries, or NumPy arrays.

These structures lacked labels, indexing, grouping, join/merge, handling missing data, etc.

Real-world datasets (CSV, JSON, Excel, SQL) are structured in rows and columns — not arrays.

So Pandas was designed to work like:

📊 Excel + 🧮 NumPy + 🗂️ SQL + 🧰 ETL tools — inside Python

# ⚙️ Where is Pandas used?

| Field              | How Pandas Helps                                        |
| ------------------ | ------------------------------------------------------- |
| Data Science       | Load, clean, explore, transform, and model data         |
| Machine Learning   | Prepare features, preprocess, manipulate large datasets |
| Finance            | Time series, stock prices, trade records                |
| Web/Data Analytics | ETL pipelines, server logs, product usage stats         |
| Healthcare         | Patient records, diagnostics, hospital statistics       |

# 🧱 What does Pandas offer at its core?

| Core Object          | Description                                   |
| -------------------- | --------------------------------------------- |
| `Series`             | 1D labeled array — like a column              |
| `DataFrame`          | 2D table — like a sheet of Excel or SQL table |
| `Panel` (deprecated) | 3D data container (replaced by MultiIndex)    |

# 🎁 And tons of utilities:

- Reading/Writing (CSV, JSON, Excel, SQL, Parquet)

- Powerful slicing/indexing/merging

- GroupBy, pivoting, reshaping

- Time series and date handling

- Missing data handling

- Statistical functions and window operations

- Built-in plotting (with matplotlib backend)

Think of Pandas like a spreadsheet that you can program, automate, and scale — with the power of Python and NumPy underneath.

In [1]:
import pandas as pd

In [35]:
## pd.Series(data)
# pd.Series(data, index=None, dtype=None, name=None, copy=False, fastpath=False)

data=[10,20,30,40,50,60,70]
s1=pd.Series(data)

In [5]:
s1 #internally it has indexing

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [7]:
s2=pd.Series(data, index=['a','b','c','d','e','f','g'], name="Numbers")

In [8]:
print(s2)

a    10
b    20
c    30
d    40
e    50
f    60
g    70
Name: Numbers, dtype: int64

In [10]:
data = {'a': 10, 'b': 20, 'c': 30}
s3 = pd.Series(data)
print(s3)

a    10
b    20
c    30
dtype: int64

In [11]:
# Create Series from NumPy array
import numpy as np

In [12]:
arr = np.array([5, 10, 15])
s4 = pd.Series(arr, index=['x', 'y', 'z'])
print(s4)

x     5
y    10
z    15
dtype: int64

In [14]:
#  Series Attributes & Properties

s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'], name='Scores')

In [15]:
print(s2)
print(s2.index)     # Index object
print(s2.values)    # NumPy array of values
print(s2.dtype)     # Data type
print(s2.name)      # Name of the Series
print(s2.shape) 
type(s2.shape)

a    10
b    20
c    30
d    40
Name: Scores, dtype: int64
Index(['a', 'b', 'c', 'd'], dtype='str')
[10 20 30 40]
int64
Scores
(4,)

tuple

#### Series Indexing & Access

In [16]:
# 1. Positional Indexing
# [10 20 30 40]
print(s2.values[0])
print(s2.values[3])

10
40

In [17]:
# iloc gets rows (and/or columns) at integer locations.

print(s2.iloc[0])

10

In [18]:
print(s2.iloc[1:3])

b    20
c    30
Name: Scores, dtype: int64

In [ ]:
# 2. Label-based Indexing

# loc gets rows (and/or columns) with particular labels.

In [11]:
# Pandas resolves s2[0] in the following order:

# Check if 0 is a label in the index
# → If yes, return by label

# If not, and if the index is not integer-based, then treat 0 as a position
# → Return item at index position 0 (first element)

# FutureWarning: Series.__getitem__ treating keys as positions is deprecated. 
# In a future version, integer keys will always be treated as 
# labels (consistent with DataFrame behavior). 
# To access a value by position, use `ser.iloc[pos]`

print(s2[0])

KeyError: 0

In [19]:
print(s2['a'])

10

In [20]:
print(s2['b'])

20

In [21]:
print(s2['c'])

30

In [ ]:
# .loc[] uses the label/index name, not position.

In [26]:
print(s2[['b', 'd']])

b    20
d    40
Name: Scores, dtype: int64

In [22]:
s2.loc[['b','d']]   #this is better to use

b    20
d    40
Name: Scores, dtype: int64

In [23]:
s2.loc[['d','a']]

d    40
a    10
Name: Scores, dtype: int64

In [24]:
s3 = pd.Series([10, 20, 30, 40])

In [28]:
s3.iloc[[1,3]]

1    20
3    40
dtype: int64

In [32]:
s3.loc[[1,3]]

1    20
3    40
dtype: int64

In [30]:
s3.loc[[1,2]]

1    20
2    30
dtype: int64

# 2. What is a DataFrame?

A DataFrame is a 2D labeled data structure with columns of potentially different types, just like a spreadsheet or SQL table.

Think of it like:

- A dict of Series

- Or a table with rows and columns

It is the core structure of pandas used for:

- Reading, cleaning, transforming, analyzing, and exporting data


### Why DataFrame?

Real-world data is usually tabular (e.g., CSV, Excel, SQL)

Rows = records

Columns = features

It supports label-based indexing, automatic alignment, missing data handling, grouping, aggregation, and more


| Concept     | Real-Life Analogy             |
| ----------- | ----------------------------- |
| `DataFrame` | Excel sheet or database table |
| `Series`    | One column of that sheet      |
| Index       | Row number or ID              |
| Columns     | Named headers                 |

In [2]:
# From a dictionary of lists - this is desired way

data = {
    'Name' : ['Hemanth', 'Aditya', 'rajbeer'],
    'Age' : [30, 31, 32],
    'City' : ['Delhi', 'Mumbai', 'Bangalore'],
    'State': ['Delhi','Maharastra','Karnataka']
}

In [3]:
df=pd.DataFrame(data)

In [29]:
print(df)

      Name  Age       City       State
0  Hemanth   30      Delhi       Delhi
1   Aditya   31     Mumbai  Maharastra
2  rajbeer   32  Bangalore   Karnataka

In [4]:
df  #the below output format shows only in notebook

      Name  Age       City       State
0  Hemanth   30      Delhi       Delhi
1   Aditya   31     Mumbai  Maharastra
2  rajbeer   32  Bangalore   Karnataka

In [5]:
# From a list of dicts - not desired way

records = [
    {'Name' : 'Hemanth', 'Age' : 30, 'City' : 'Delhi'},
    {'Name' : 'Aditya', 'Age' : 31, 'City' : 'Mumbai'},
    {'Name' : 'Rajbeer', 'Age' : 32, 'City' : 'Bangalore'}
]

df = pd.DataFrame(records)
print(df)

      Name  Age       City
0  Hemanth   30      Delhi
1   Aditya   31     Mumbai
2  Rajbeer   32  Bangalore

In [45]:
# From NumPy arrays (if all columns are of the same type)

arr = np.array([[1, 2], [3, 4], [5, 6]])
df = pd.DataFrame(arr, columns=['A', 'B'])
print(df)

   A  B
0  1  2
1  3  4
2  5  6

In [6]:
# Accessing Data

data = {
    'Name' : ['Hemanth', 'Aditya', 'rajbeer'],
    'Age' : [30, 31, 32],
    'City' : ['Delhi', 'Mumbai', 'Bangalore']
}

df = pd.DataFrame(data)

In [7]:
df

      Name  Age       City
0  Hemanth   30      Delhi
1   Aditya   31     Mumbai
2  rajbeer   32  Bangalore

In [8]:
df['Name'] # Series ( single column )

0    Hemanth
1     Aditya
2    rajbeer
Name: Name, dtype: str

In [9]:
df[['Name','Age']] # dataframe with 2 columns

      Name  Age
0  Hemanth   30
1   Aditya   31
2  rajbeer   32

In [10]:
## i want to get first row
df.loc[0]

Name    Hemanth
Age          30
City      Delhi
Name: 0, dtype: object

In [11]:
df.iloc[0]

Name    Hemanth
Age          30
City      Delhi
Name: 0, dtype: object

In [12]:
print(df['Name']) # Series (a column)
print("===========")
print(df[['Name', 'Age']]) # DataFrame with two columns
print("===========")
print(df.iloc[0]) # Row by integer index label or position
print("===========")
print(df.loc[0])  # Row by index label

0    Hemanth
1     Aditya
2    rajbeer
Name: Name, dtype: str
===========
      Name  Age
0  Hemanth   30
1   Aditya   31
2  rajbeer   32
===========
Name    Hemanth
Age          30
City      Delhi
Name: 0, dtype: object
===========
Name    Hemanth
Age          30
City      Delhi
Name: 0, dtype: object

# Working with real dataset

In [13]:
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [14]:
df = pd.read_csv(titanic_dataset_github_url)

In [15]:
df.head() # shows first 5 rows from dataframe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
type(df)

pandas.DataFrame

In [17]:
df.tail() # shows last 5 rows from dataframe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [58]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [18]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [19]:
df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [20]:
df.shape

(891, 12)

In [21]:
dir(df)  ## to get attributes of datafrome

['Age',
 'Cabin',
 'Embarked',
 'Fare',
 'Name',
 'Parch',
 'PassengerId',
 'Pclass',
 'Sex',
 'SibSp',
 'Survived',
 'T',
 'Ticket',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [22]:
display(df.head(3))
display(df.head(1))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [23]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [24]:
df[["Name" , 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [25]:
df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [50]:
df.loc[0,'Name']

'Braund, Mr. Owen Harris'

In [51]:
df.iloc[0,3] #oth row 3rd value

'Braund, Mr. Owen Harris'

In [52]:
# First 5 rows
df.iloc[:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
df.iloc[0:5, 3]

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [27]:
df.iloc[0:5, 3]

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

# 5. Conditional Selection (Boolean Indexing)

In [28]:
# Passengers older than 70

df['Age'] > 70 # Boolean index of passengers > 70 (True) else False

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [29]:
df[df['Age']>70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [30]:
older_passengers = df[df['Age'] > 70]
display(older_passengers.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [57]:
older_passengers.shape

(5, 12)

In [32]:
older_passengers.info() #info() is method of dataFrame

<class 'pandas.DataFrame'>
Index: 5 entries, 96 to 851
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  5 non-null      int64
 1   Survived     5 non-null      int64
 2   Pclass       5 non-null      int64
 3   Name         5 non-null      str
 4   Sex          5 non-null      str
 5   Age          5 non-null      float64
 6   SibSp        5 non-null      int64
 7   Parch        5 non-null      int64
 8   Ticket       5 non-null      str
 9   Fare         5 non-null      float64
 10  Cabin        2 non-null      str
 11  Embarked     5 non-null      str
dtypes: float64(2), int64(5), str(5)
memory usage: 520.0 bytes

In [31]:
older_passengers.describe()

       PassengerId  Survived    Pclass        Age  SibSp  Parch       Fare
count     5.000000  5.000000  5.000000   5.000000    5.0    5.0   5.000000
mean    438.200000  0.200000  1.800000  73.300000    0.0    0.0  25.936680
std     328.292096  0.447214  1.095445   3.993745    0.0    0.0  18.086844
min      97.000000  0.000000  1.000000  70.500000    0.0    0.0   7.750000
25%     117.000000  0.000000  1.000000  71.000000    0.0    0.0   7.775000
50%     494.000000  0.000000  1.000000  71.000000    0.0    0.0  30.000000
75%     631.000000  0.000000  3.000000  74.000000    0.0    0.0  34.654200
max     852.000000  1.000000  3.000000  80.000000    0.0    0.0  49.504200

In [60]:
older_passengers['PassengerId'].describe()

count      5.000000
mean     438.200000
std      328.292096
min       97.000000
25%      117.000000
50%      494.000000
75%      631.000000
max      852.000000
Name: PassengerId, dtype: float64

In [33]:
# Females who survived
# Sex = female AND survived = 1

df[(df['Sex'] == 'female') & (df['Survived'] == 1)] # --> True / False

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [34]:
# get Name & Age of Females who survived
# df[["Name" , 'Age']]
female_survivors_subset = df[(df['Sex'] == 'female') & (df['Survived'] == 1)][['Name', 'Age']]
female_survivors_subset.head()

                                                Name   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

In [35]:
# get Name & Age of Females who survived using loc

# df.loc[label, ['Name', 'Age']]

df.loc[(df['Sex'] == 'female') & (df['Survived'] == 1), ['Name', 'Age']]

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
887                       Graham, Miss. Margaret Edith  19.0

[233 rows x 2 columns]

# 6. Slicing Rows and Columns Together

In [36]:
# Rows 0 to 4, only Name and Age
# df.loc[0:4, ['Name', 'Age']]
df.loc[:4, ['Name', 'Age']]

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [37]:
df.head()[['Name','Age']]

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [38]:
df.head(3)[['Name','Age']] #but i want first 3 rows and 1st 2 columsn

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0

In [39]:
# First 3 rows and first 2 columns
# df.iloc[:3, :2]
df.iloc[0:3, 0:2]

   PassengerId  Survived
0            1         0
1            2         1
2            3         1

In [90]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [66]:
# First 3 rows and column Name as the first column and then then Survived column
df.iloc[0:3, [3, 1]]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1

In [40]:
df.loc[0:3, ['Name', 'Survived']]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1

In [94]:
df.head(4)[['Name','Survived']]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)         1

In [95]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Set Index (Optional)

In [67]:
df_by_passenger_id = df.set_index('PassengerId')  # we are setting passengerId as index here

In [68]:
df_by_passenger_id.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [69]:
df_by_passenger_id.iloc[0]  #getting 1 row of data

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Sex                            male
Age                            22.0
SibSp                             1
Parch                             0
Ticket                    A/5 21171
Fare                           7.25
Cabin                           NaN
Embarked                          S
Name: 1, dtype: object

In [70]:
df_by_passenger_id.loc[1]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Sex                            male
Age                            22.0
SibSp                             1
Parch                             0
Ticket                    A/5 21171
Fare                           7.25
Cabin                           NaN
Embarked                          S
Name: 1, dtype: object

In [71]:
df_by_passenger_id = df_by_passenger_id.reset_index() # to remove the index on passenger id.

In [72]:
df_by_passenger_id.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

# Assignment-1

In [ ]:
# Assignment-1

# I want you to download below csv using python

# create a class

# create a obj s and call the obj.download(URL, path_to_download="data")

# you are not suppose to use pandas or numpy

# Only use python and libraries like request and other

# titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

In [41]:
## 25-06-2026
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [42]:
df = pd.read_csv(titanic_dataset_github_url)

In [43]:
df_by_passenger_id = df.set_index('PassengerId')

In [44]:
df_by_passenger_id.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [45]:
df_by_name = df.set_index('Name')

In [46]:
df_by_name

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [47]:
df_by_name.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [48]:
print(df_by_name.loc['Andersson, Mr. Anders Johan']) #loc will work on labels as we know name, just checking with names

PassengerId        14
Survived            0
Pclass              3
Sex              male
Age              39.0
SibSp               1
Parch               5
Ticket         347082
Fare           31.275
Cabin             NaN
Embarked            S
Name: Andersson, Mr. Anders Johan, dtype: object

# Are Subsets Views or Copies in Pandas?

In pandas, whether you get a view (linked to original DataFrame) or a copy (independent) 
depends on how you slice or filter — and it’s not always obvious.

- .iloc always returns a copy (safe, independent subset.)
- .loc may return a view (especially if indexing on labels)
    ```bash
    subset = df.loc[df['Sex'] == 'male']
    This is like the earlier filtering — might be a view.

    so..
    subset = df.loc[df['Sex'] == 'male'].copy()

    ```

| Situation                          | View or Copy? | Should you use `.copy()`? |
| ---------------------------------- | ------------- | ------------------------- |
| `.iloc[]` slicing                  | Mostly Copy   | Optional                  |
| `.loc[]` slicing                   | May be View   | Recommended               |
| Filtering with condition `df[...]` | May be View   | Recommended               |
| You plan to modify the subset      | Use `.copy()` | YES                       |

In [ ]:
# instead of below

subset = df[df['Sex'] == 'male']
subset['Age'] = subset['Age'] + 1

# SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame in previous version

In [81]:
subset = df[df['Sex'] == 'male'].copy()
subset['Age'] += 1

In [82]:
subset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,36.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,55.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,3.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,29.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,26.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,28.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,27.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,33.0,0,0,370376,7.7500,NaN,Q

# Set Index vs Re - index

| Feature       | `set_index()`                               | `reindex()`                                          |
| ------------- | ------------------------------------------- | ---------------------------------------------------- |
| What it does  | **Moves a column** to become the index      | **Changes the row/column labels** of a DataFrame     |
| Main Use Case | Change the row labels using existing column | Match to new labels, add/remove/reorder rows/columns |
| Affects index | Yes – creates a **new index from a column** | Yes – but just **remaps or aligns to new index**     |
| Adds NaNs?    | No – only restructures                      | Yes – can insert NaNs for new labels                 |

In [ ]:
# NAN -> Not a number

# 1. set_index() — Use a column as the new index

In [83]:
df_by_name = df.set_index('Name')
print(df_by_name.loc['Allen, Miss. Elisabeth Walton'])  # Now 'Name' is index

PassengerId         731
Survived              1
Pclass                1
Sex              female
Age                29.0
SibSp                 0
Parch                 0
Ticket            24160
Fare           211.3375
Cabin                B5
Embarked              S
Name: Allen, Miss. Elisabeth Walton, dtype: object

In [84]:
df_by_name=df_by_name.reset_index()

In [85]:
df_by_name

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

# 2. reindex() — Conform to a new index/column structure

In [86]:
sales_jan = pd.DataFrame({
    'Sales': [250, 400, 300]
}, index=['Store_A', 'Store_B', 'Store_C'])

sales_jan

         Sales
Store_A    250
Store_B    400
Store_C    300

In [87]:
sales_feb = pd.DataFrame({
    'Sales': [260, 310]
}, index=['Store_A', 'Store_C'])

sales_feb

         Sales
Store_A    260
Store_C    310

In [ ]:
❌ Problem: Indexes are mismatched! (above 2 dataframes)

You cannot safely do operations like subtraction or direct comparison unless indexes are aligned.

✅ 🛠 Solution: Use reindex() to align!

In [88]:
common_index = sales_jan.index

print(common_index)

Index(['Store_A', 'Store_B', 'Store_C'], dtype='str')

In [89]:
sales_feb_aligned = sales_feb.reindex(common_index)

sales_feb_aligned

         Sales
Store_A  260.0
Store_B    NaN
Store_C  310.0

In [90]:
sales_diff = sales_feb_aligned['Sales'] - sales_jan['Sales']

sales_diff

Store_A    10.0
Store_B     NaN
Store_C    10.0
Name: Sales, dtype: float64

In [91]:
sales_feb_aligned = sales_feb.reindex(common_index, fill_value=0) # we use fill_value=0 to do correct calculations

sales_feb_aligned

         Sales
Store_A    260
Store_B      0
Store_C    310

In [92]:
sales_diff = sales_feb_aligned['Sales'] - sales_jan['Sales']

sales_diff

Store_A     10
Store_B   -400
Store_C     10
Name: Sales, dtype: int64

# For column

In [95]:
source_a = pd.DataFrame({
    'Product': ['Laptop', 'Tablet', 'Phone'],
    'Price': [1000, 500, 800],
    'Stock': [30, 50, 100]
})

source_a

  Product  Price  Stock
0  Laptop   1000     30
1  Tablet    500     50
2   Phone    800    100

In [96]:
source_b = pd.DataFrame({
    'Price': [980, 520, 810],
    'Product': ['Laptop', 'Tablet', 'Phone']
})

source_b

   Price Product
0    980  Laptop
1    520  Tablet
2    810   Phone

In [97]:
aligned_b = source_b.reindex(columns=source_a.columns, fill_value = 0)

aligned_b

  Product  Price  Stock
0  Laptop    980      0
1  Tablet    520      0
2   Phone    810      0

In [98]:
stock_diff = source_a['Stock'] - aligned_b['Stock']

stock_diff

0     30
1     50
2    100
Name: Stock, dtype: int64

# Iteration in Pandas

In pandas, iteration refers to looping over rows or columns of a DataFrame or Series. While pandas is optimized for vectorized operations, sometimes we need to loop — for example, for conditional logic, debugging, or generating complex values.

In [49]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Delhi', 'Mumbai', 'Chennai']
})

In [100]:
df

      Name  Age     City
0    Alice   25    Delhi
1      Bob   30   Mumbai
2  Charlie   35  Chennai

In [51]:
for index, row in df.iterrows():
    print(f"{index}: {row['Name']} lives in {row['City']} and is {row['Age']} years old.")

0: Alice lives in Delhi and is 25 years old.
1: Bob lives in Mumbai and is 30 years old.
2: Charlie lives in Chennai and is 35 years old.

In [52]:
for row in df.itertuples():
    print(row)
    print(row.Index)
    print(f"{row.Name} lives in {row.City}, and is {row.Age} years old.", end='\n\n')

Pandas(Index=0, Name='Alice', Age=25, City='Delhi')
0
Alice lives in Delhi, and is 25 years old.

Pandas(Index=1, Name='Bob', Age=30, City='Mumbai')
1
Bob lives in Mumbai, and is 30 years old.

Pandas(Index=2, Name='Charlie', Age=35, City='Chennai')
2
Charlie lives in Chennai, and is 35 years old.

In [53]:
# Iterating Over Columns

for col in df.columns:
    print(f"Column: {col}")
    print(df[col].values, end='\n\n')

Column: Name
<StringArray>
['Alice', 'Bob', 'Charlie']
Length: 3, dtype: str

Column: Age
[25 30 35]

Column: City
<StringArray>
['Delhi', 'Mumbai', 'Chennai']
Length: 3, dtype: str

In [55]:
list(df.columns)

['Name', 'Age', 'City']

In [57]:
df.columns

Index(['Name', 'Age', 'City'], dtype='str')

# Conditional Example: Add Column with Custom Logic

Based on age column, i want to create a new column that will classify people as 'young' or 'senior'

In [60]:
categories=[]

for idx,row in df.iterrows():
    #print(row)
    #print(row['Age'])

    if row["Age"] < 40:
        categories.append("young")
    else:
        categories.append("senior")
    
df["Category"] = categories
df.head()

      Name  Age     City Category
0    Alice   25    Delhi    young
1      Bob   30   Mumbai    young
2  Charlie   35  Chennai    young

# Better Way: Vectorized / Apply (*** very important in machine learning ***** apply)

In [61]:
df['Catergory_vectorized_1']=df['Age'].apply(lambda age: 'young' if age < 40 else 'senior')

In [62]:
df.head()

      Name  Age     City Category Catergory_vectorized_1
0    Alice   25    Delhi    young                  young
1      Bob   30   Mumbai    young                  young
2  Charlie   35  Chennai    young                  young

In [63]:
categorized_age_lambda = lambda age: 'young' if age < 40 else 'senior'
df["Catergory_vectorized_2"]=df['Age'].apply(categorized_age_lambda)
df.head()

,Name,Age,City,Category,Catergory_vectorized_1,Catergory_vectorized_2
0,Alice,25,Delhi,young,young,young
1,Bob,30,Mumbai,young,young,young
2,Charlie,35,Chennai,young,young,young

In [65]:
def categorize_age_function(age):
    # if age < 40:
    #     return 'young'
    # else :
    #     return 'senior'
    return 'young' if age < 40 else 'senior'

df['Category_vectorized_3'] = df['Age'].apply(categorize_age_function)

df.head()

,Name,Age,City,Category,Catergory_vectorized_1,Catergory_vectorized_2,Category_vectorized_3
0,Alice,25,Delhi,young,young,young,young
1,Bob,30,Mumbai,young,young,young,young
2,Charlie,35,Chennai,young,young,young,young

In [66]:
for i in df[['Age', 'City']].iterrows():
    print(i)

(0, Age        25
City    Delhi
Name: 0, dtype: object)
(1, Age         30
City    Mumbai
Name: 1, dtype: object)
(2, Age          35
City    Chennai
Name: 2, dtype: object)

In [67]:
df.columns

Index(['Name', 'Age', 'City', 'Category', 'Catergory_vectorized_1',
       'Catergory_vectorized_2', 'Category_vectorized_3'],
      dtype='str')

In [ ]:
# # axis = 0
# keep column constant and get all rows

# # axis = 1
# keep row constant and get all columns

In [69]:
def check_if_delhi_and_young(row):
    #print(row)
    city = row['City']
    age = row['Age']
    if city == 'Delhi':
        if age < 40:
            return True
        else :
            return False
    else:
        return False
    # return 'young' if age < 40 else 'senior'

df['If_young_and_from_delhi'] = df.apply(check_if_delhi_and_young, axis=1)

In [70]:
df

,Name,Age,City,Category,Catergory_vectorized_1,Catergory_vectorized_2,Category_vectorized_3,If_young_and_from_delhi
0,Alice,25,Delhi,young,young,young,young,True
1,Bob,30,Mumbai,young,young,young,young,False
2,Charlie,35,Chennai,young,young,young,young,False

# Sorting in Pandas

Sorting helps you organize your data for better readability, analysis, and logical operations — whether by index or actual data values.

### Why Sorting Matters

You might want to:

- See top-performing products (e.g., highest sales)

- Order records by name/date

- Prepare data before merging or visualizing

### Two Main Types of Sorting
1. sort_values() → Sort by data values
2. sort_index() → Sort by index (row or column labels)

# 1. sort_values() → Sort by data values

# syntax

```bash
DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, na_position='last')
```

| Argument      | Purpose                                 |
| ------------- | --------------------------------------- |
| `by`          | Column label(s) to sort by              |
| `axis`        | 0 = rows (default), 1 = columns         |
| `ascending`   | True = low to high, False = high to low |
| `inplace`     | True = modify current object            |
| `na_position` | 'first' or 'last' for NaNs              |

In [74]:
# Example of inplace

class Calculator:
    def __init__(self, a):
        self.a = a
    def add(self, b):
        c = self.a + b
        return c
    def inplace_add(self, b):
        self.a = self.a + b
        return self.a

In [72]:
c_cal=Calculator(10)

In [73]:
c_cal.a

10

In [75]:
c_cal.add(10)

20

In [76]:
c_cal.a = c_cal.add(10) # inplace False

In [77]:
c_cal.a

20

In [78]:
c_cal.inplace_add(10) # inplace True

30

In [79]:
c_cal.a

30

In [80]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_github_url)

In [81]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [82]:
sorted_df=df.sort_values(by='Age')

In [87]:
sorted_df.head(10)['Age']

803    0.42
755    0.67
644    0.75
469    0.75
78     0.83
831    0.83
305    0.92
386    1.00
172    1.00
183    1.00
Name: Age, dtype: float64

In [90]:
sorted_df.iloc[200:300,:]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
491,492,0,3,"Windelov, Mr. Einar",male,21.0,0,0,SOTON/OQ 3101317,7.2500,NaN,S
624,625,0,3,"Bowen, Mr. David John ""Dai""",male,21.0,0,0,54636,16.1000,NaN,S
836,837,0,3,"Pasic, Mr. Jakob",male,21.0,0,0,315097,8.6625,NaN,S
501,502,0,3,"Canavan, Miss. Mary",female,21.0,0,0,364846,7.7500,NaN,Q
395,396,0,3,"Johansson, Mr. Erik",male,22.0,0,0,350052,7.7958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
370,371,1,1,"Harder, Mr. George Achilles",male,25.0,1,0,11765,55.4417,E50,C
784,785,0,3,"Ali, Mr. William",male,25.0,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S
134,135,0,2,"Sobey, Mr. Samuel James Hayden",male,25.0,0,0,C.A. 29178,13.0000,NaN,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.0,0,0,348123,7.6500,F G73,S

In [91]:
print(df['Age'].dtype)

float64

In [92]:
## to change Age datatype from float64 to int, we use astype()
df['Age']=df['Age'].astype('int64')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

In [ ]:
df['Age'] = df['Age'].fillna(0).astype('int64') # the fillna() used to replace all "Nan" to 0 in Age column

In [94]:
print(df[['Name', 'Age']].tail(10))

                                         Name  Age
881                        Markun, Mr. Johann   33
882              Dahlberg, Miss. Gerda Ulrika   22
883             Banfield, Mr. Frederick James   28
884                    Sutehall, Mr. Henry Jr   25
885      Rice, Mrs. William (Margaret Norton)   39
886                     Montvila, Rev. Juozas   27
887              Graham, Miss. Margaret Edith   19
888  Johnston, Miss. Catherine Helen "Carrie"    0
889                     Behr, Mr. Karl Howell   26
890                       Dooley, Mr. Patrick   32

In [95]:
sorted_df = df.sort_values(by='Age')
print(sorted_df[['Name', 'Age']].tail(20))

                                          Name  Age
625                      Sutton, Mr. Frederick   61
570                         Harris, Mr. George   62
829  Stone, Mrs. George Nelson (Martha Evelyn)   62
252                  Stead, Mr. William Thomas   62
555                         Wright, Mr. George   62
275          Andrews, Miss. Kornelia Theodosia   63
483                     Turkula, Mrs. (Hedwig)   63
545               Nicholson, Mr. Arthur Ernest   64
438                          Fortune, Mr. Mark   64
54              Ostby, Mr. Engelhart Cornelius   65
456                  Millet, Mr. Francis Davis   65
280                           Duane, Mr. Frank   65
33                       Wheadon, Mr. Edward H   66
116                       Connors, Mr. Patrick   70
745               Crosby, Capt. Edward Gifford   70
672                Mitchell, Mr. Henry Michael   70
493                    Artagaveytia, Mr. Ramon   71
96                   Goldschmidt, Mr. George B   71
851                        Svensson, Mr. Johan   74
630       Barkworth, Mr. Algernon Henry Wilson   80

# Example 2: Sort by multiple columns

First sort by Pclass (ascending), then by Fare (descending)

In [96]:
df_sorted = df.sort_values(by=['Pclass', 'Fare'], ascending=[True, False])

In [97]:
df_sorted.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35,0,0,PC 17755,512.3292,B101,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263.0000,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23,3,2,19950,263.0000,C23 C25 C27,S

# 2. sort_index() – Sorting by index

This is useful when you’ve set a meaningful index and want to restore or arrange it.

```bash
DataFrame.sort_index(axis=0, ascending=True, inplace=False)
```

axis=0 → Sort rows

axis=1 → Sort columns

In [98]:
df_sort_2 = df.set_index('PassengerId')
df_sorted_by_index = df_sort_2.sort_index()

In [99]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [100]:
df_sorted_by_index.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

# Sorting Columns Alphabetically

In [101]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [102]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [103]:
df[['Ticket', 'Name']]

               Ticket                                               Name
0           A/5 21171                            Braund, Mr. Owen Harris
1            PC 17599  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    STON/O2. 3101282                             Heikkinen, Miss. Laina
3              113803       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4              373450                           Allen, Mr. William Henry
..                ...                                                ...
886            211536                              Montvila, Rev. Juozas
887            112053                       Graham, Miss. Margaret Edith
888        W./C. 6607           Johnston, Miss. Catherine Helen "Carrie"
889            111369                              Behr, Mr. Karl Howell
890            370376                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [104]:
sorted(df.columns)

['Age',
 'Cabin',
 'Embarked',
 'Fare',
 'Name',
 'Parch',
 'PassengerId',
 'Pclass',
 'Sex',
 'SibSp',
 'Survived',
 'Ticket']

In [105]:
df_sorted = df[sorted(df.columns)]

df_sorted.head()

,Age,Cabin,Embarked,Fare,Name,Parch,PassengerId,Pclass,Sex,SibSp,Survived,Ticket
0,22,NaN,S,7.2500,"Braund, Mr. Owen Harris",0,1,3,male,1,0,A/5 21171
1,38,C85,C,71.2833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,2,1,female,1,1,PC 17599
2,26,NaN,S,7.9250,"Heikkinen, Miss. Laina",0,3,3,female,0,1,STON/O2. 3101282
3,35,C123,S,53.1000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,4,1,female,1,1,113803
4,35,NaN,S,8.0500,"Allen, Mr. William Henry",0,5,3,male,0,0,373450

# Working with Text Data in Pandas

In [106]:
# Lowercase
df['Name'].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [107]:
# Uppercase
df['Name'].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: str

In [108]:
# Capitalize
df['Name'].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [109]:
# String Length
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [110]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_github_url)

In [111]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [117]:
df['Name'].str.replace("Mr.","Sir.",regex=False).head()

0                             Braund, Sir. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                            Allen, Sir. William Henry
Name: Name, dtype: str

In [118]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [119]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [120]:
df.loc[1]['Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [121]:
df.loc[1,'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [125]:
# i want to remove the paranthesis from name
start=df.loc[1,'Name'].find("(")

In [126]:
end=df.loc[1,'Name'].find(")")

In [127]:
df.loc[1,'Name'][0:start]+df.loc[1,'Name'][end+1:]

'Cumings, Mrs. John Bradley '

In [128]:
def remove_substring(name):
    start = name.find("(")
    end = name.find(")")
    new_name = name[0:start] + name[end+1:]
    new_name = new_name.strip()
    return new_name

In [129]:
df["Name_trimmed"] = df["Name"].apply(remove_substring)

In [132]:
df['Name_trimmed'].head()

0      Braund, Mr. Owen HarriBraund, Mr. Owen Harris
1                         Cumings, Mrs. John Bradley
2        Heikkinen, Miss. LainHeikkinen, Miss. Laina
3                       Futrelle, Mrs. Jacques Heath
4    Allen, Mr. William HenrAllen, Mr. William Henry
Name: Name_trimmed, dtype: str

In [133]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [134]:
df.loc[1, 'Name_trimmed']

'Cumings, Mrs. John Bradley'

In [136]:
# Replace Substrings with Regex : regular expression

# * means zero or more
# . match any character
# "\(.*\)"

# windows : \\
#df['Name'].str.replace(r"\(.*\)", "HELLO", regex=True).head()

df['Name'].str.replace(r"\(.*\)","",regex=True).head()

0          Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley
2           Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath
4         Allen, Mr. William Henry
Name: Name, dtype: str

In [138]:
import re

def is_valid_email(email):
    # Practical pattern for common use cases
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    
    # Use fullmatch to ensure the entire string is evaluated
    if re.fullmatch(pattern, email):
        return True
    return False

# Test cases
print(is_valid_email("user.name@example.com"))  # True
print(is_valid_email("user@sub.domain.org"))    # True
print(is_valid_email("invalid-email@com"))      # False (short TLD)
print(is_valid_email("mahesh_puppala@optum.com"))

True
True
False
True

| Part | Meaning                                                              |
| ---- | -------------------------------------------------------------------- |
| `r`  | Raw string literal — tells Python **not to interpret** `\` as escape |
| `\(` | Escaped `(` — matches a literal opening parenthesis                  |
| `.*` | Dot `.` matches **any character**, and `*` means **zero or more**    |
| `\)` | Escaped `)` — matches a literal closing parenthesis                  |

In [ ]:
# hello@ghail@abc.com

# python logic

# regex pattern

In [139]:
import re

In [140]:
def is_valid_email(email):
    # Regex Breakdown:
    # ^[a-zA-Z0-9._%+-]+ : Alphanumeric + common symbols in username
    # @                  : Mandatory @ symbol
    # [a-zA-Z0-9.-]+     : Alphanumeric, dots, or hyphens in domain
    # \.[a-zA-Z]{2,}$    : Must end with a dot followed by 2 or more letters
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    
    # re.fullmatch returns a Match object if valid, otherwise None
    if re.fullmatch(pattern, email):
        return True
    return False

# Test cases
emails = ["user@example.com", "invalid-email", "name.surname@sub.domain.org", "hello@ghail@abc.com"]
for e in emails:
    print(f"{e}: {'Valid' if is_valid_email(e) else 'Invalid'}")

user@example.com: Valid
invalid-email: Invalid
name.surname@sub.domain.org: Valid
hello@ghail@abc.com: Invalid

# Split and Access Elements

In [141]:
df['Name'][0]

'Braund, Mr. Owen Harris'

In [143]:
df.loc[0]['Name']

'Braund, Mr. Owen Harris'

In [147]:
df['Name'].str.split(',')[0]

['Braund', ' Mr. Owen Harris']

In [ ]:
df['Name'].str.split(' ')[0] ## split by space

['Braund,', 'Mr.', 'Owen', 'Harris']

In [149]:
df['Name'].str.split().str[0]

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: Name, Length: 891, dtype: object

In [150]:
print(df['Name'].str.split()[0][0])

Braund,

# Strip Spaces

In [ ]:
df['Name'].str.strip()  #to remove spaces from trailing left and righ side

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [152]:
df['Name'].str.lstrip() # to remove left spaces from Name column

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [153]:
df['Name'].str.rstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

# Find Position of Substring

In [154]:
df['Name'].str.find("Mr")

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [155]:
# "Miss"
# Count passengers with “Miss” in name
#contains() is method to get the count

count = df['Name'].str.contains("Miss").sum() # here False is 0 and True is 1
print("Number of 'Miss':", count)

Number of 'Miss': 182

In [156]:
data = {
    'Name': [
        'John Doe', 'Jane Smith', 'Emily Johnson',
        'Robert Brown', 'Anna-Marie Lee'
    ],
    'Email': [
        'john@example.com', 'jane.smith@work.org',
        'emily_j@data.net', 'robertb@yahoo.com',
        'anna.lee@company.co'
    ]
}

df = pd.DataFrame(data)

In [157]:
df.head()

             Name                Email
0        John Doe     john@example.com
1      Jane Smith  jane.smith@work.org
2   Emily Johnson     emily_j@data.net
3    Robert Brown    robertb@yahoo.com
4  Anna-Marie Lee  anna.lee@company.co

In [165]:
df['Name'].str.pad(width=20, side='left', fillchar='*')

0    ************John Doe
1    **********Jane Smith
2    *******Emily Johnson
3    ********Robert Brown
4    ******Anna-Marie Lee
Name: Name, dtype: str

# Categorical Data in Pandas

### 📌 What is Categorical Data?

Categorical data is textual or labeled data that represents discrete categories.

In [166]:
class_data={
    "Name":['A','B','C','D'],
    "Groups":['G1','G2','G3','G4']
}

In [168]:
class_df=pd.DataFrame(class_data)

In [169]:
class_df

  Name Groups
0    A     G1
1    B     G2
2    C     G3
3    D     G4

In [ ]:
# df['Groups'] > "G4"

In [ ]:
# G3, G1, G2, G4 --> Higher to lower
# df['Groups'] > "G4"
# G1 > G4 --> True

In [171]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Groups  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [ ]:
class_df['Group_cat']=pd.Categorical(
    class_df['Groups'],
    categories=['G3','G1','G2','G4'], # Custom order lower to higher (Ascending)
    # 'G3' : 1, 'G1' : 2, 'G2' : 3, 'G4' : 4
    ordered=True
)

In [173]:
class_df

  Name Groups Group_cat
0    A     G1        G1
1    B     G2        G2
2    C     G3        G3
3    D     G4        G4

In [174]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      str
 1   Groups     4 non-null      str
 2   Group_cat  4 non-null      category
dtypes: category(1), str(2)
memory usage: 404.0 bytes

In [176]:
class_df['Group_cat'].cat.categories

Index(['G3', 'G1', 'G2', 'G4'], dtype='str')

In [ ]:
class_df['Group_cat']>"G4"

0    False
1    False
2    False
3    False
Name: Group_cat, dtype: bool

In [178]:
class_df['Group_cat']>="G4"

0    False
1    False
2    False
3     True
Name: Group_cat, dtype: bool

In [179]:
class_df

  Name Groups Group_cat
0    A     G1        G1
1    B     G2        G2
2    C     G3        G3
3    D     G4        G4

In [180]:
df = pd.read_csv(titanic_dataset_github_url)

In [181]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [182]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [183]:
df['Embarked'].unique() # the port where a passenger boarded the ship, indicated by a single-letter code
# C (Cherbourg)
# Q (Queenstown)
# S (Southampton)

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [184]:
df['Embarked'] = df['Embarked'].fillna("N")

In [186]:
df['Embarked'].unique()
# C (Cherbourg) --> 1000000
# Q (Queenstown) --> 5000000
# S (Southampton) ---> 100000
# N --> Not provided ---> 000000

# N, S, C, Q

# Find all the passenger >  100000 > S

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [187]:
df['Embarked_cust_cat']=pd.Categorical(
    df['Embarked'],
    categories=['N','S','C','Q'], # Custom order lower to higher (Ascending)
    # 'N' : 1, 'S' : 2, 'C' : 3, 'Q' : 4
    ordered=True
)

In [188]:
df['Embarked_cust_cat'].cat.categories

Index(['N', 'S', 'C', 'Q'], dtype='str')

In [189]:
df['Embarked_cust_cat'] > 'S'

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889     True
890     True
Name: Embarked_cust_cat, Length: 891, dtype: bool

In [190]:
df['Embarked_cust_cat'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked_cust_cat, dtype: category
Categories (4, str): ['N' < 'S' < 'C' < 'Q']

In [ ]:
df['Embarked_cust_cat'].cat.codes.head() #here cat.codes gives respective order in form of number as defined in categories dtype

0    1
1    2
2    1
3    1
4    1
dtype: int8

In [192]:
# df['Sex']

# i want you to convert the values of Sex column and encode them in 0 & 1

df['Sex'].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [ ]:
## we can do other way as below 

# df['Sex_cat_custom'] = df['Sex'].astype('category').cat.codes

# df['Sex_cat_custom'] = df['Sex'].replace(['female', 'male'], [0, 1])

# df['Sex_cat_custom'] = df['Sex'].apply(lambda sex: 1 if sex == 'male' else 0)

In [193]:
df['Sex_cat']=pd.Categorical(
    df['Sex'],
    categories=['female','male'], # Custom order lower to higher (Ascending)
    # 'G3' : 1, 'G1' : 2, 'G2' : 3, 'G4' : 4
    ordered=True
)

In [194]:
df['Sex_cat']

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex_cat, Length: 891, dtype: category
Categories (2, str): ['female' < 'male']

In [195]:
df['Sex_cat'].cat.codes.head()

0    1
1    0
2    0
3    0
4    1
dtype: int8

In [196]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Embarked_cust_cat,Sex_cat
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,S,male
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C,female
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,S,female
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,S,female
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,S,male

# Date Functionality in Pandas

In [198]:
df = pd.DataFrame({
    'event': ['Concert', 'Conference', 'Wedding'],
    'date': ['2025-01-01', '2025-03-15', '2025-07-20']
})

In [199]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   event   3 non-null      str
 1   date    3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [200]:
df

        event        date
0     Concert  2025-01-01
1  Conference  2025-03-15
2     Wedding  2025-07-20

In [ ]:
df['date_pandas']=pd.to_datetime(df['date'])
# format: optional format (e.g. '%d/%m/%Y')

In [202]:
df

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15
2     Wedding  2025-07-20  2025-07-20

In [203]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event        3 non-null      str
 1   date         3 non-null      str
 2   date_pandas  3 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [204]:
df.head()

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15
2     Wedding  2025-07-20  2025-07-20

In [205]:
df['date_pandas'].dt.year

0    2025
1    2025
2    2025
Name: date_pandas, dtype: int32

In [206]:
df['date_pandas'].dt.month

0    1
1    3
2    7
Name: date_pandas, dtype: int32

In [207]:
df['date_pandas'].dt.day

0     1
1    15
2    20
Name: date_pandas, dtype: int32

In [208]:
df['date_pandas'].dt.weekday

0    2
1    5
2    6
Name: date_pandas, dtype: int32

In [209]:
df['date_pandas'].dt.day_name()

0    Wednesday
1     Saturday
2       Sunday
Name: date_pandas, dtype: str

In [210]:
df

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15
2     Wedding  2025-07-20  2025-07-20

In [211]:
df[df['date_pandas'] > '2025-04-01']

     event        date date_pandas
2  Wedding  2025-07-20  2025-07-20

In [212]:
df[df['date_pandas'].between('2025-01-01', '2025-06-01')]

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15

# Creating Datetime Ranges

Other frequencies:

'M' → month end

'MS' → month start

'W' → weekly

'H', 'T', 'S' → hour, minute, second

In [213]:
pd.date_range(start='2026-02-01', end='2026-02-10', freq='D')

DatetimeIndex(['2026-02-01', '2026-02-02', '2026-02-03', '2026-02-04',
               '2026-02-05', '2026-02-06', '2026-02-07', '2026-02-08',
               '2026-02-09', '2026-02-10'],
              dtype='datetime64[us]', freq='D')

In [219]:
pd.date_range(start='2024-01-01', end='2024-03-30', freq='ME')

DatetimeIndex(['2024-01-31', '2024-02-29'], dtype='datetime64[us]', freq='ME')

In [220]:
pd.date_range(start='2024-01-01', end='2024-03-31', freq='ME')

DatetimeIndex(['2024-01-31', '2024-02-29', '2024-03-31'], dtype='datetime64[us]', freq='ME')

In [223]:
pd.date_range(start='2024-01-01', end='2024-03-31', freq='MS')

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01'], dtype='datetime64[us]', freq='MS')

# Date Arithmetic

In [224]:
df['next_week'] = df['date_pandas'] + pd.Timedelta(days=7)

In [225]:
pd.Timedelta(days=7)

Timedelta('7 days 00:00:00')

In [226]:
pd.Timestamp.today()

Timestamp('2026-03-03 20:39:14.422738')

In [227]:
df.head()

        event        date date_pandas  next_week
0     Concert  2025-01-01  2025-01-01 2025-01-08
1  Conference  2025-03-15  2025-03-15 2025-03-22
2     Wedding  2025-07-20  2025-07-20 2025-07-27

In [228]:
df['days_to_event'] = df['date_pandas'] - pd.Timestamp.today()

In [229]:
df.head()

        event        date date_pandas  next_week              days_to_event
0     Concert  2025-01-01  2025-01-01 2025-01-08 -427 days +03:20:13.127927
1  Conference  2025-03-15  2025-03-15 2025-03-22 -354 days +03:20:13.127927
2     Wedding  2025-07-20  2025-07-20 2025-07-27 -227 days +03:20:13.127927

In [230]:
# PANDAS COMPLETED

#=================================================================